export const translations = {
  en: {
    // Common
    loading: 'Loading...',
    error_occurred: 'An error occurred',
    last_updated: 'Last updated',
    unlimited: 'Unlimited',
    confirm_delete: 'Delete',
    just_received: 'Just now',
    has_new: 'New',

    // Auth
    sign_in: 'Sign In',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    username: 'Username',
    btn_signin: 'Sign In',
    btn_register: 'Create Account',
    btn_loading: 'Please wait...',
    login_code_link: '🔑 Have a code? Login with code',
    code_title: 'Login with Code',
    code_subtitle: 'Enter the code provided by your admin',
    code_back: '← Back',
    code_btn: 'Login',

    // Navbar
    nav_otps: 'OTPs',
    nav_gmail: 'Gmail Accounts',
    nav_subusers: 'Sub-users',
    nav_admin: 'Admin Panel',
    nav_logout: 'Logout',

    // OTP Grid
    otp_title: 'OTPs',
    otp_new: 'New',
    otp_copy: 'Copy',
    otp_copied: 'Copied!',
    otp_refresh: '↻ Refresh',
    otp_empty_title: 'Waiting for OTP...',
    otp_empty_sub: 'System polls every 15 seconds',
    otp_refresh_in: 'refresh in',
    otp_has_new: 'New',

    // Gmail
    gmail_title: 'Gmail Accounts',
    gmail_subtitle: 'System polls OTP from connected Gmail every 15 seconds',
    gmail_connect: '+ Connect Gmail',
    gmail_connecting: 'Connecting...',
    gmail_delete: 'Remove',
    gmail_empty_title: 'No Gmail connected',
    gmail_empty_sub: 'Click "+ Connect Gmail" to get started',
    gmail_otps: 'OTPs',
    gmail_last_poll: 'last poll',
    gmail_confirm_delete: 'Remove {email} from system?',

    // Sub-users
    sub_title: 'Sub-users',
    sub_subtitle: 'Each person gets a login code — sees only assigned Gmail OTPs',
    sub_create: '+ Create Sub-user',
    sub_cancel: '✕ Cancel',
    sub_create_title: 'Create New Sub-user',
    sub_create_sub: 'System auto-generates a login code',
    sub_name_label: 'Name / Username',
    sub_name_placeholder: 'e.g. John, worker01',
    sub_btn_create: 'Create',
    sub_btn_creating: 'Creating...',
    sub_empty_title: 'No Sub-users yet',
    sub_empty_sub: 'Click "+ Create Sub-user" to start',
    sub_code_label: 'Login Code',
    sub_code_hint: 'Go to /code and enter this code',
    sub_gmail_label: 'Accessible Gmail',
    sub_gmail_none: 'No Gmail assigned — will not see any OTP',
    sub_gmail_full: 'All Gmails assigned',
    sub_gmail_no_gmail: '⚠ No Gmail connected — add one from Gmail Accounts tab first',
    sub_gmail_select: 'Select Gmail to assign...',
    sub_assign: '+ Assign',
    sub_delete: 'Delete',
    sub_toggle_off: 'Disable',
    sub_toggle_on: 'Enable',
    sub_confirm_delete: 'Delete "{name}"?',
    sub_active: 'active',
    sub_inactive: 'inactive',

    // Admin
    admin_users: 'Users',
    admin_active_gmails: 'Active Gmails',
    admin_total_otps: 'Total OTPs',
    admin_title: 'Users',
    admin_back: '← Back',
    admin_disable: 'Disable',
    admin_enable: 'Enable',
    admin_plan_label: 'Subscription Plan',
    admin_gmails_label: 'Gmail Accounts',
    admin_sub_label: 'Sub-users',
    admin_joined: 'Joined',
    admin_limit: 'Limit',
    admin_assigned: 'Gmail assigned',
    admin_empty: 'No users yet',
    admin_no_gmail: 'No Gmail connected',
    admin_no_sub: 'No sub-users',

    // Plan limits
    plan_limit_free: '1 Gmail · 1 Sub-user',
    plan_limit_basic: '5 Gmails · 10 Sub-users',
    plan_limit_pro: 'Unlimited',

    // Toast
    toast_gmail_connected: 'Connected {email} successfully',
    toast_gmail_error: 'Failed to connect Gmail. Please try again.',
  },

  th: {
    // Common
    loading: 'กำลังโหลด...',
    error_occurred: 'เกิดข้อผิดพลาด',
    last_updated: 'อัปเดตล่าสุด',
    unlimited: 'ไม่จำกัด',
    confirm_delete: 'ลบ',
    just_received: 'เพิ่งได้รับ',
    has_new: 'ใหม่',

    // Auth
    sign_in: 'เข้าสู่ระบบ',
    register: 'สมัครสมาชิก',
    email: 'อีเมล',
    password: 'รหัสผ่าน',
    username: 'ชื่อผู้ใช้',
    btn_signin: 'เข้าสู่ระบบ',
    btn_register: 'สมัครสมาชิก',
    btn_loading: 'กำลังดำเนินการ...',
    login_code_link: '🔑 มีรหัสอยู่แล้ว? เข้าสู่ระบบด้วยรหัส',
    code_title: 'เข้าสู่ระบบด้วยรหัส',
    code_subtitle: 'ใส่รหัสที่ได้รับจากผู้ดูแล',
    code_back: '← กลับ',
    code_btn: 'เข้าสู่ระบบ',

    // Navbar
    nav_otps: 'OTPs',
    nav_gmail: 'Gmail Accounts',
    nav_subusers: 'Sub-users',
    nav_admin: 'Admin Panel',
    nav_logout: 'ออก',

    // OTP Grid
    otp_title: 'OTPs',
    otp_new: 'ใหม่',
    otp_copy: 'Copy',
    otp_copied: 'Copied!',
    otp_refresh: '↻ refresh',
    otp_empty_title: 'รอ OTP เข้า...',
    otp_empty_sub: 'ระบบ poll ทุก 15 วินาที',
    otp_refresh_in: 'refresh ใน',
    otp_has_new: 'มีใหม่',

    // Gmail
    gmail_title: 'Gmail Accounts',
    gmail_subtitle: 'ระบบ poll OTP จาก Gmail ที่เชื่อมต่อทุก 15 วินาที',
    gmail_connect: '+ เชื่อมต่อ Gmail',
    gmail_connecting: 'กำลังเชื่อมต่อ...',
    gmail_delete: 'ลบ',
    gmail_empty_title: 'ยังไม่มี Gmail ที่เชื่อมต่อ',
    gmail_empty_sub: 'กดปุ่ม "+ เชื่อมต่อ Gmail" เพื่อเริ่มต้น',
    gmail_otps: 'OTPs',
    gmail_last_poll: 'poll ล่าสุด',
    gmail_confirm_delete: 'ลบ {email} ออกจากระบบ?',

    // Sub-users
    sub_title: 'Sub-users',
    sub_subtitle: 'แต่ละคนได้รหัส login — เห็น OTP เฉพาะ Gmail ที่ assign ให้',
    sub_create: '+ สร้าง Sub-user',
    sub_cancel: '✕ ยกเลิก',
    sub_create_title: 'สร้าง Sub-user ใหม่',
    sub_create_sub: 'ระบบสร้างรหัส login อัตโนมัติ',
    sub_name_label: 'ชื่อ / Username',
    sub_name_placeholder: 'เช่น ป้อม, หนุ่ม, worker01',
    sub_btn_create: 'สร้าง',
    sub_btn_creating: 'กำลังสร้าง...',
    sub_empty_title: 'ยังไม่มี Sub-user',
    sub_empty_sub: 'กด "+ สร้าง Sub-user" เพื่อเริ่มต้น',
    sub_code_label: 'รหัส Login',
    sub_code_hint: 'เปิด /code แล้วกรอกรหัสนี้',
    sub_gmail_label: 'Gmail ที่เห็นได้',
    sub_gmail_none: 'ยังไม่ได้ assign — จะไม่เห็น OTP ใดเลย',
    sub_gmail_full: 'Assign ครบทุก Gmail แล้ว',
    sub_gmail_no_gmail: '⚠ ยังไม่มี Gmail — ไปเพิ่มที่แท็บ Gmail Accounts ก่อน',
    sub_gmail_select: 'เลือก Gmail...',
    sub_assign: '+ Assign',
    sub_delete: 'ลบ',
    sub_toggle_off: 'ปิด',
    sub_toggle_on: 'เปิด',
    sub_confirm_delete: 'ลบ "{name}"?',
    sub_active: 'ใช้งานได้',
    sub_inactive: 'ถูกปิด',

    // Admin
    admin_users: 'Users',
    admin_active_gmails: 'Active Gmails',
    admin_total_otps: 'Total OTPs',
    admin_title: 'Users',
    admin_back: '← กลับ',
    admin_disable: 'Disable',
    admin_enable: 'Enable',
    admin_plan_label: 'Subscription Plan',
    admin_gmails_label: 'Gmail Accounts',
    admin_sub_label: 'Sub-users',
    admin_joined: 'สมัครเมื่อ',
    admin_limit: 'Limit',
    admin_assigned: 'Gmail assigned',
    admin_empty: 'ยังไม่มี user สมัครเข้ามา',
    admin_no_gmail: 'ยังไม่มี Gmail',
    admin_no_sub: 'ยังไม่มี sub-user',

    // Plan limits
    plan_limit_free: '1 Gmail · 1 Sub-user',
    plan_limit_basic: '5 Gmails · 10 Sub-users',
    plan_limit_pro: 'ไม่จำกัด',

    // Toast
    toast_gmail_connected: 'เชื่อมต่อ {email} สำเร็จ',
    toast_gmail_error: 'เชื่อมต่อ Gmail ไม่สำเร็จ ลองใหม่อีกครั้ง',
  },
}
